version: '3.8'

services:
  annotation:
    build: ./annotation-service
    container_name: "annotation-service"
    image: annotation-service:latest
    platform: linux/amd64
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - aws-network

  prediction:
    build: ./service-predict
    container_name: "prediction-service"
    image: prediction-service:latest
    platform: linux/amd64
    networks:
      - aws-network

  api-gateway:
    container_name: "api-gateway"
    image: api-gateway:latest
    build: ./web-api
    command: npm run start:prod
    ports:
      - "3000:3000"
    networks:
      - aws-network
    restart: unless-stopped
    environment:
      - SERVICE_PORT=3000
      - LEX_URL=http://annotation:8080/api/annotate
      - PREDICT_URL=http://prediction:5000/predict
    depends_on:
      - annotation
      - prediction

  mongodb:
    image: mongo:5.0.6
    container_name: MongoDB
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:${MONGO_PORT}"
    networks:
      - aws-network

networks:
  aws-network: