version: '3.8'

services:
  annotation:
    build: ./annotation-service
    # container_name: "annotation-service"
    image: annotation-service:latest
    env_file:
      - .env
    depends_on:
      - mongodb
    expose:
      - "8080"
    networks:
      - aws-network
    restart: unless-stopped

  prediction:
    build: ./prediction-service
    # container_name: "prediction-service"
    image: prediction-service:latest
    expose:
      - "5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - aws-network
    restart: unless-stopped

  api-gateway:
    build: ./web-api
    container_name: "api-gateway"
    image: api-gateway:latest
    command: npm run start:prod
    depends_on:
      - nginx
    ports:
      - "3000:3000"
    networks:
      - aws-network
    environment:
      - SERVICE_PORT=3000
      - LEX_URL=http://nginx:4000/api/annotate
      - PREDICT_URL=http://nginx:4000/api/v1/prediction
    restart: unless-stopped
  
  training:
    build: ./training-service
    container_name: "training-service"
    image: training-service:latest
    env_file:
      - .env
    ports:
    # todo: use "expose" instead of ports, so port is not exposed to public via host
      - "6061:6061"
    networks:
      - aws-network
    depends_on:
      - prediction
      - mongodb
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - annotation
      - prediction
    networks:
      - aws-network
    # todo: use "expose" instead of ports, so port is not exposed to public via host
    ports:
      - "4000:4000"
    restart: unless-stopped


  mongodb:
    image: mongo:5.0.6
    container_name: MongoDB
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    # since this DB is also used during test runs in GitHub CI, port is exposed on host machine
    ports:
      - "27017:${MONGO_PORT}"
    networks:
      - aws-network
    restart: unless-stopped

  demo-frontend:
    build: ./demo-frontend
    container_name: "demo-frontend"
    image: demo-frontend:latest
    depends_on:
      - api-gateway
    environment:
      - VITE_API_URL=http://api-gateway:3000
    ports: 
      - "8081:8081"
    networks:
      - aws-network


networks:
  aws-network: