version: "3.8"

services:
    demo-frontend:
        build:
            context: ./demo-frontend
            args:
                - VITE_HIGHLIGHT_URL=http://hack3rz-aws.switzerlandnorth.azurecontainer.io:${WEB_API_PORT}/api/v1/highlight
        container_name: "demo-frontend"
        image: hack3rzacr.azurecr.io/demo-frontend
        domainname: hack3rz-aws
        env_file:
            - .env
        ports:
            - "${DEMO_FRONTEND_PORT}:${DEMO_FRONTEND_PORT}"
        depends_on:
            - web-api
        deploy:
            resources:
                reservations:
                    cpus: "0.5"
                    memory: 3G
                limits:
                    cpus: "0.5"
                    memory: 3G

    web-api:
        build: ./web-api
        container_name: "web-api"
        image: hack3rzacr.azurecr.io/web-api
        domainname: hack3rz-aws
        command: npm run start:prod
        env_file:
            - .env.prod
        environment:
            - LEX_URL=http://hack3rz-aws.switzerlandnorth.azurecontainer.io:${ANNOTATION_SERVICE_PORT}/api/v1/annotation
            - PREDICT_URL=http://hack3rz-aws.switzerlandnorth.azurecontainer.io:${PREDICTION_SERVICE_PORT}/api/v1/prediction
        ports:
            - "${WEB_API_PORT}:${WEB_API_PORT}"
        depends_on:
            - prediction
            - annotation
        restart: always
        deploy:
            resources:
                reservations:
                    cpus: "0.5"
                    memory: 3G
                limits:
                    cpus: "0.5"
                    memory: 3G

    annotation:
        build: ./annotation-service
        container_name: annotation-service
        image: hack3rzacr.azurecr.io/annotation-service
        domainname: hack3rz-aws
        env_file:
            - .env.prod
        ports:
            - "${ANNOTATION_SERVICE_PORT}:${ANNOTATION_SERVICE_PORT}"
        restart: always
        deploy:
            resources:
                reservations:
                    cpus: "0.5"
                    memory: 3G
                limits:
                    cpus: "0.5"
                    memory: 3G

    prediction:
        build: ./prediction-service
        container_name: "prediction-service"
        image: hack3rzacr.azurecr.io/prediction-service
        domainname: hack3rz-aws
        env_file:
            - .env.prod
        ports:
            - "${PREDICTION_SERVICE_PORT}:${PREDICTION_SERVICE_PORT}"
        restart: always
        deploy:
            resources:
                reservations:
                    cpus: "0.5"
                    memory: 3G
                limits:
                    cpus: "0.5"
                    memory: 3G

    training:
        build: ./training-service
        container_name: "training-service"
        image: hack3rzacr.azurecr.io/training-service
        domainname: hack3rz-aws
        env_file:
            - .env.prod
        ports:
            - "${TRAINING_SERVICE_PORT}:${TRAINING_SERVICE_PORT}"
        restart: always
        deploy:
            resources:
                reservations:
                    cpus: "0.5"
                    memory: 3G
                limits:
                    cpus: "0.5"
                    memory: 3G
