name: Annotation Service DockerHub
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'annotation-service/**'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: DockerHub Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: annotation-service
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: annotation-service/
          file: annotation-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/annotation-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/annotation-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/annotation-service:buildcache,mode=max
