name: Web Api Service DockerHub
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - 'web-api/**'
jobs:
  build:
    name: DockerHub Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/web-api
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: web-api/
          file: web-api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/web-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/web-api:buildcache,mode=max
